3 qubo formulations lecture
quantum-ods/qmlcourse pull request #365
Opened 2021-12-24 20:22 UTC by dmburd

2021-12-25 19:48 UTC, vtrokhymenko reviewed
http://54.89.156.216/lecture_qubo_linreg_svm_kmeans/_build/html/book/problems2qml/qubo_linreg_svm_kmeans.html#k

2021-12-25 19:48 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +- $N$ -- количество обучающих примеров (семплов) в обучающем наборе, $N \in \{1, 2, \dotsc\}$;
дважды «обучающих»

2021-12-25 19:48 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +- $d$ -- количество признаков (*features*) для семплов в обучающем наборе, $d \in \{1, 2, \dotsc\}$;
лучше всё же «семплов» -> «примеры» и так везде в лекции ну или на что-то более русское

2021-12-25 19:48 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +- $X$ -- тренировочный набор, содержит по одному семплу в каждой из $N$ строк, каждая строка содержит $d$ значений признаков, $X \in \mathbb{R}^{N \times d}$;
```suggestion
- $X$ -- тренировочный набор, содержит по одному семплу в каждой из $N$ строк, которая содержит $d$ значений признаков, $X \in \mathbb{R}^{N \times d}$;
```

2021-12-25 19:48 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +где $M$ -- натуральное число, $z$ -- бинарный вектор решения, $A \in \mathbb{R}^{M \times M}$ -- QUBO-матрица с действительными элементами, $b \in \mathbb{R}^{M}$ -- QUBO-вектор. Как отмечалось в пре
```suggestion
где $M$ -- натуральное число, $z$ -- бинарный вектор решения, $A \in \mathbb{R}^{M \times M}$ -- QUBO-матрица с действительными элементами, $b \in \mathbb{R}^{M}$ -- QUBO-вектор. Как отмечалось в предыдущей лекции, при $z_i \in \{0,1\}$ выполняется равенство $z_i^2 = z_i$, так что линейные члены в {eq}`eqn:general_qubo_in_paper` можно включить в квадратичные, но этого делать не будем, т.к. для целей этой лекции и для лучшего понимания удобнее сохранить минимизируемую квадратичную форму именно в виде {eq}`eqn:general_qubo_in_paper`.
```

2021-12-25 19:48 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +В задаче линейной регрессии мы предполагаем, что зависимость ground truth ответов от признаков семплов приближенно линейная:
```suggestion
В задаче линейной регрессии предполагается, что зависимость ground truth ответов от признаков семплов приближенно линейная:
```

2021-12-25 19:48 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +В задаче линейной регрессии мы предполагаем, что зависимость ground truth ответов от признаков семплов приближенно линейная:
и не хочешь «ground truth» нормально на русском написать? соответственно в лекции также изменить

2021-12-25 19:48 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +где $y_i^{(pred)}$ -- предсказываемое значение, $y_i$ -- ground truth значение, $\braket{\cdot, \cdot}$ -- скалярное произведение. Удобно сразу избавиться от слагаемого $b$ (*bias*), добавив единицу
что за `\cdot` в $\braket{\cdot, \cdot}$?

2021-12-25 19:48 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +где $y_i^{(pred)}$ -- предсказываемое значение, $y_i$ -- ground truth значение, $\braket{\cdot, \cdot}$ -- скалярное произведение. Удобно сразу избавиться от слагаемого $b$ (*bias*), добавив единицу
```suggestion
где $y_i^{(pred)}$ -- предсказываемое значение, $y_i$ -- ground truth значение, $\braket{\cdot, \cdot}$ -- скалярное произведение. Удобно сразу избавиться от слагаемого $b$ (*bias*), добавив единицу к набору признаков. Тогда он окажется включенным в веса $w$, а тренировочный набор будет иметь по $(d+1)$ признаков на семпл: $X \in \mathbb{R}^{N \times (d+1)}$. Требуется найти веса $w$, при которых квадрат евклидовой нормы невязки минимален:
```

2021-12-25 19:48 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Если $\left( X^T X \right)^{-1}$ не существует, нужно вычислить [псевдообратную](https://ru.wikipedia.org/wiki/Псевдообратная_матрица) матрицу. ВременнАя сложность решения задачи линейной регрессии р
тут точно везде в `d^2` правильно стоят цифры?

2021-12-25 19:48 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Наша цель -- найти вектор $w$, компоненты которого -- действительные числа. Но в QUBO-формулировке необходимо представить решение в виде вектора с бинарными компонентами. Как это сделать? Конечно, на
`fixed-point` по-русски не хочешь написать? причем даже wiki имеет соответствующую страницу. в лекции дальше также используется это

2021-12-25 19:48 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Для исходной задачи регрессии {eq}`eqn:lin_reg_orig` количество значений в датасете $X$ равно $\mathcal{O}(N d)$. Мы ввели $K$ бинарных переменных для каждого из $(d+1)$ весов. Значит, получилось $\m
```suggestion
Для исходной задачи регрессии {eq}`eqn:lin_reg_orig` количество значений в датасете $X$ равно $\mathcal{O}(N d)$. Выше ввели $K$ бинарных переменных для каждого из $(d+1)$ весов. Значит, получилось $\mathcal{O}(K d)$ переменных в QUBO-формулировке {eq}`eqn:lin_reg_qubo_2`. Для решения задачи требуется $\mathcal{O}(K^2 d^2)$ кубитов (см. {cite}`embeddingqubo2019`), это *space complexity* в рассматриваемом подходе.
```

2021-12-25 19:48 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Для исходной задачи регрессии {eq}`eqn:lin_reg_orig` количество значений в датасете $X$ равно $\mathcal{O}(N d)$. Мы ввели $K$ бинарных переменных для каждого из $(d+1)$ весов. Значит, получилось $\m
`space complexity` также на русском не хочешь?

2021-12-25 19:48 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +3. Время для выполнения квантового отжига. Существуют теоретические оценки времени для получения точного решения, но более практично рассматривать случай, когда мы довольствуемся просто достаточно вы
```suggestion
3. Время для выполнения квантового отжига. Существуют теоретические оценки времени для получения точного решения, но более практично рассматривать случай, когда можно просто довольствоваться достаточно высокой вероятностью (скажем, 99%) получения оптимального решения. Для современных квантовых компьютеров D-Wave с ограниченным числом кубитов на практике получается, что время отжига и число повторений можно считать константами.
```

2021-12-25 19:48 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Классический SVM подробно описан в соответствующей [лекции](classicsvm). Рассматривается тренировочный набор $X \in \mathbb{R}^{N \times d}$ и набор ground truth меток $Y \in \{-1, +1\}^{N}$. Нужно р
```suggestion
Классический SVM подробно описан в соответствующей [лекции](classicsvm). Рассматривается тренировочный набор $X \in \mathbb{R}^{N \times d}$ и набор ground truth меток $Y \in \{-1, +1\}^{N}$. Нужно решить задачу бинарной классификации, найдя веса $w \in \mathbb{R}^{d}$ и байес $b \in \mathbb{R}$, при которых классификатор $a(x_i) = \text{sign} \left( w^T x_i + b \right)$ допускает как можно меньше ошибок на обучающей выборке.
```

2021-12-25 19:48 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Двойственная задача {eq}`svmDual` в наших обозначениях принимает вид
```suggestion
Двойственная задача {eq}`svmDual` в текущих обозначениях принимает вид
```

2021-12-25 19:48 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +не зависит. Семплы, соответствующие $\lambda_i > 0$, называются *опорными*. В статье {cite}`qubo3mlproblems2021` при переходе к QUBO-формулировке ограничение $\sum_{i} \lambda_i y_i = 0$ отбрасывают
```suggestion
не зависит. Семплы, соответствующие $\lambda_i > 0$, называются *опорными*. В статье {cite}`qubo3mlproblems2021` при переходе к QUBO-формулировке ограничение $\sum_{i} \lambda_i y_i = 0$ отбрасывают без всяких объяснений. Возможно, это обосновывается тем соображением, что в "хороших" задачах классификации количество опорных семплов обычно невелико (таким образом, сумма $\sum_{i} \lambda_i y_i$ в последнем условии в {eq}`eqn:svm_dual_2` содержит достаточно мало нетривиальных $(\lambda_i \neq 0)$ слагаемых).
```

2021-12-25 19:48 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Бинарные компоненты логично рассматривать как индикаторы наличия или отсутствия соответствующих степеней двойки в бинарном представлении каждого действительного числа. Введем вектор-столбец $P$ (*pre
`precision vector`

2021-12-25 19:48 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Вектор $P$ содержит $m + 1 + l = K$ элементов. При подходящем выборе $m$ и $l$ достаточно точно выполняется равенство
выше вроде было `$(m + 1 + l) \cdot2 = K$` или это о другом?

2021-12-25 19:48 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +и матрицу $\mathcal{P}$ (*precision matrix*):
`precision matrix` на русском не? дальше в лекции также упоминается

2021-12-25 19:48 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +\lambda = \mathcal{P} \tilde{\lambda}
тут это «приближенно» не правильно отобразить?

2021-12-25 19:48 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +В итоге временнАя сложность $\mathcal{O}(N^2 K^2)$. $K$ можно считать константой, т.к. она зависит только от диапазона и желаемой точности представления $\lambda$, не зависит от параметров самой зада
```suggestion
В итоге временнАя сложность $\mathcal{O}(N^2 K^2)$. $K$ можно считать константой, т.к. зависит только от диапазона и желаемой точности представления $\lambda$ и не зависит от параметров самой задачи классификации. Тогда получается временная сложность $\mathcal{O}(N^2)$, что гораздо лучше оценки $\mathcal{O}(N^3)$ в классическом случае.
```

2021-12-25 19:48 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Нам потребуется избавиться от этих ограничений, чтобы получить *unconstrained* задачу. Для этого, как обычно, введем в минимизируемую квадратичную форму штрафы за нарушение ограничений. Вернемся к эт
```suggestion
Для этого потребуется избавиться от выше ограничений, чтобы получить *unconstrained* задачу. Для этого, как обычно, введем в минимизируемую квадратичную форму штрафы за нарушение ограничений. Вернемся к этому через пару абзацев.
```

2021-12-25 19:48 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Нам потребуется избавиться от этих ограничений, чтобы получить *unconstrained* задачу. Для этого, как обычно, введем в минимизируемую квадратичную форму штрафы за нарушение ограничений. Вернемся к эт
`unconstrained` в «неограниченный» или как лучше не?

2021-12-25 19:48 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Задача {eq}`eqn:kmeans_equal_clusters` содержит $\mathcal{O}(N d)$ значений в данных и $\mathcal{O}(N)$ переменных. В QUBO-формулировке мы вводим по $k$ бинарных переменных для каждой исходной. Получ
```suggestion
Задача {eq}`eqn:kmeans_equal_clusters` содержит $\mathcal{O}(N d)$ значений в данных и $\mathcal{O}(N)$ переменных. В QUBO-формулировке вводим по $k$ бинарных переменных для каждой исходной. Получается $\mathcal{O}(N k)$ переменных, а значит, требуется $\mathcal{O}(N^2 k^2)$ кубитов.
```

2021-12-25 20:49 UTC, SemyonSinchenko commented on qmlcourseRU/_bibliography/references.bib
> +}
Идеально было бы вставить новые записи по алфавиту. Сейчас bib-файл сортирован - мы пришли к этому после многократных проблем с мерж-конфликтами и сломанными билдами из-за дублей. Когда bib сортирован, дубли убираются оч легко, как и мерж-конфликты. Еще круче было бы сохранить единое форматирование (как во всем файле), но это мелочи.

2021-12-26 07:42 UTC, alexey-pronkin commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Классический SVM подробно описан в соответствующей [лекции](classicsvm). Рассматривается тренировочный набор $X \in \mathbb{R}^{N \times d}$ и набор ground truth меток $Y \in \{-1, +1\}^{N}$. Нужно р
так не говорят, говорят вектор смещения или просто константа

2021-12-26 07:49 UTC, dmburd commented on qmlcourseRU/_bibliography/references.bib
> +}
Отсортировал: https://github.com/quantum-ods/qmlcourse/pull/365/commits/d053445f8741982d964cdefb2a8d2b31e683402c

2021-12-26 07:54 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +- $X$ -- тренировочный набор, содержит по одному семплу в каждой из $N$ строк, каждая строка содержит $d$ значений признаков, $X \in \mathbb{R}^{N \times d}$;
Нет, это речевая ошибка. Нет слова, которое точно согласуется с "которая".
Мне кажется, так, как было -- нормально.

2021-12-26 07:58 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +и матрицу $\mathcal{P}$ (*precision matrix*):
Это я специально не стал переводить, а оставил на английском и курсивом, чтобы сохранить термин из оригинальной статьи. Считай, дал точную цитату, чтобы читатель быстро увидел соответствие между лекцией и статьёй.
Да и как ты хочешь перевести? "Матрица точности"? Это же совсем не годится. Я не придумал адекватного перевода. (Често говоря, сам термин в оригинале по-английски -- странный.)

2021-12-26 08:01 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +\lambda = \mathcal{P} \tilde{\lambda}
Думал об этом, но дальше-то ставятся именно знаки равенства. Тащить везде \approx не хочется. В статье вообще \approx не встречается, я это вставлял исключительно для понимания того, в чём именно заключается приближение.

2021-12-26 08:05 UTC, SemyonSinchenko approved these changes

2021-12-26 08:08 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Нам потребуется избавиться от этих ограничений, чтобы получить *unconstrained* задачу. Для этого, как обычно, введем в минимизируемую квадратичную форму штрафы за нарушение ограничений. Вернемся к эт
Почему ты хочешь всегда и везде избавляться от местоимений? С ними нормально всё, хорошо читается, гладко звучит. 
"выше ограничений" -- речевая ошибка.
"чтобы получить неограниченную задачу" -- плохо звучит, необщепринято. Я специально оставил unconstrained в соответствии с буквой "U" в QUBO. Мы же не заменяем везде QUBO на КОБО ("квадратичная оптимизация без ограничений")?

2021-12-26 08:10 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +где $y_i^{(pred)}$ -- предсказываемое значение, $y_i$ -- ground truth значение, $\braket{\cdot, \cdot}$ -- скалярное произведение. Удобно сразу избавиться от слагаемого $b$ (*bias*), добавив единицу
\cdot -- это такой placeholder, т.е. показывает, что на этом месте должна быть переменная (или выражение).

2021-12-26 08:16 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +где $y_i^{(pred)}$ -- предсказываемое значение, $y_i$ -- ground truth значение, $\braket{\cdot, \cdot}$ -- скалярное произведение. Удобно сразу избавиться от слагаемого $b$ (*bias*), добавив единицу
Мне кажется, не страшно оставить некоторые повторения ради точности утверждений. Ты хочешь подставить "он" вместо "bias". Почему "он"? Видимо, ты считаешь, что bias -- мужского рода. Почему так?
А вот в предыдущем предложении написано "слагаемое" (средний род). Заменяем на "оно", читаем результат. Мне не нравится, читатель будет лишние несколько секунд думать, что имеется в виду.

2021-12-26 08:17 UTC, alexey-pronkin requested changes
Хорошая лекция, замечания не супер значительные
Еще я не помню, как мы обозначаем ударения в словах, в книгах все-таки принято использовать спец знаки, а мы можем тут техом красиво сделать (`\'буква` или `\acute{буква})`, но ради простоты можно и просто большие буквы оставить, хз как jbook будет это трактовать.

2021-12-26 08:17 UTC, alexey-pronkin commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +не зависит. Семплы, соответствующие $\lambda_i > 0$, называются *опорными*. В статье {cite}`qubo3mlproblems2021` при переходе к QUBO-формулировке ограничение $\sum_{i} \lambda_i y_i = 0$ отбрасывают
Я уже подзабыл, но кажется, что это объясняется тем, что в оптимальной точке это условие выполнено для всех ламбд. А так как мы приближаем hinge loss кусочно линейной функцией, то по сути у нас выпуклая квадратичная задача с одной оптимальной точкой (если выборка данных не вырождает задачу). (Если бы была плохая задача, то мы бы все найденные кандидады в оптимальные точки проверяли бы этим условием).
Можно посмотреть в нашей же лекции по SVM. Вообще хорошо бы разобраться и написать правильно, потому что сейчас объяснение совсем не точное.

2021-12-26 08:21 UTC, alexey-pronkin commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +не зависит. Семплы, соответствующие $\lambda_i > 0$, называются *опорными*. В статье {cite}`qubo3mlproblems2021` при переходе к QUBO-формулировке ограничение $\sum_{i} \lambda_i y_i = 0$ отбрасывают
призывается @Yorko

2021-12-26 08:24 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Если $\left( X^T X \right)^{-1}$ не существует, нужно вычислить [псевдообратную](https://ru.wikipedia.org/wiki/Псевдообратная_матрица) матрицу. ВременнАя сложность решения задачи линейной регрессии р
Вроде всё правильно.

2021-12-26 08:25 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Для исходной задачи регрессии {eq}`eqn:lin_reg_orig` количество значений в датасете $X$ равно $\mathcal{O}(N d)$. Мы ввели $K$ бинарных переменных для каждого из $(d+1)$ весов. Значит, получилось $\m
Вот тут без местоимения хуже, чем с местоимением, я считаю.

2021-12-26 08:27 UTC, alexey-pronkin commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Если $\left( X^T X \right)^{-1}$ не существует, нужно вычислить [псевдообратную](https://ru.wikipedia.org/wiki/Псевдообратная_матрица) матрицу. ВременнАя сложность решения задачи линейной регрессии р
Подтвержаю, что вроде верно

2021-12-26 08:34 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +1. Затраты времени для конвертации задачи регрессии в QUBO-формулировку. Здесь получаем $\mathcal{O}(N K^2 d^2)$ (проверьте это, оценив число умножений, необходимых для вычисления $\mathcal{P}^T X^T
А я наоборот хотел, чтобы были приложены умственные усилия :) Это упражнение.
Пусть читатель вспомнит, какие размерности у Х, у \mathcal{P} и рассмотрит произведение четырёх матриц.

2021-12-26 08:45 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Бинарные компоненты логично рассматривать как индикаторы наличия или отсутствия соответствующих степеней двойки в бинарном представлении каждого действительного числа. Введем вектор-столбец $P$ (*pre
Это цитата для понимания связи со статьёй. Переводу не подлежит.

2021-12-26 08:48 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Вектор $P$ содержит $m + 1 + l = K$ элементов. При подходящем выборе $m$ и $l$ достаточно точно выполняется равенство
Выше были элементы обоих знаков, т.е. было в 2 раза больше, чем здесь. Обозначение $K$ можно одно и то же, это не особо важно.

2021-12-26 08:57 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +- $N$ -- количество обучающих примеров (семплов) в обучающем наборе, $N \in \{1, 2, \dotsc\}$;
https://github.com/quantum-ods/qmlcourse/pull/365/commits/9bc313e8938976e735a23e814c870ecdc197c214

2021-12-26 08:58 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Наша цель -- найти вектор $w$, компоненты которого -- действительные числа. Но в QUBO-формулировке необходимо представить решение в виде вектора с бинарными компонентами. Как это сделать? Конечно, на
https://github.com/quantum-ods/qmlcourse/pull/365/commits/9bc313e8938976e735a23e814c870ecdc197c214

2021-12-26 08:58 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Для исходной задачи регрессии {eq}`eqn:lin_reg_orig` количество значений в датасете $X$ равно $\mathcal{O}(N d)$. Мы ввели $K$ бинарных переменных для каждого из $(d+1)$ весов. Значит, получилось $\m
`space complexity` https://github.com/quantum-ods/qmlcourse/pull/365/commits/9bc313e8938976e735a23e814c870ecdc197c214

2021-12-26 08:58 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Классический SVM подробно описан в соответствующей [лекции](classicsvm). Рассматривается тренировочный набор $X \in \mathbb{R}^{N \times d}$ и набор ground truth меток $Y \in \{-1, +1\}^{N}$. Нужно р
"константа" https://github.com/quantum-ods/qmlcourse/pull/365/commits/9bc313e8938976e735a23e814c870ecdc197c214

2021-12-26 08:59 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +В итоге временнАя сложность $\mathcal{O}(N^2 K^2)$. $K$ можно считать константой, т.к. она зависит только от диапазона и желаемой точности представления $\lambda$, не зависит от параметров самой зада
https://github.com/quantum-ods/qmlcourse/pull/365/commits/9bc313e8938976e735a23e814c870ecdc197c214
"и" вставил.
С местоимением гораздо лучше, чем без.

2021-12-26 09:02 UTC, Randl commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Если $\left( X^T X \right)^{-1}$ не существует, нужно вычислить [псевдообратную](https://ru.wikipedia.org/wiki/Псевдообратная_матрица) матрицу. ВременнАя сложность решения задачи линейной регрессии р
Но ведь \left( X^T X \right)^{-1} X^T и есть псевдообратная?

2021-12-26 09:08 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Если $\left( X^T X \right)^{-1}$ не существует, нужно вычислить [псевдообратную](https://ru.wikipedia.org/wiki/Псевдообратная_матрица) матрицу. ВременнАя сложность решения задачи линейной регрессии р
Нет.

2021-12-26 09:13 UTC, Randl commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Если $\left( X^T X \right)^{-1}$ не существует, нужно вычислить [псевдообратную](https://ru.wikipedia.org/wiki/Псевдообратная_матрица) матрицу. ВременнАя сложность решения задачи линейной регрессии р
https://en.wikipedia.org/wiki/Moore%E2%80%93Penrose_inverse#Linear_least-squares

2021-12-26 09:15 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +не зависит. Семплы, соответствующие $\lambda_i > 0$, называются *опорными*. В статье {cite}`qubo3mlproblems2021` при переходе к QUBO-формулировке ограничение $\sum_{i} \lambda_i y_i = 0$ отбрасывают
Я специально посмотрел видеолекцию Воронцова. 
Условия 0 <= lambda_i <= C задают гиперкуб. Условие sum(lambda_i y_i) задают гиперплоскость. Пересечение (т.е. сечение) -- выпуклое множество. Именно на нём минимизируется квадратичная форма. А не во всём гиперкубе.
Почему вдруг результат оптимизации в гиперкубе окажется на гиперплоскости? 
Ограничение sum(lambda_i y_i) существенно.

2021-12-26 09:20 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Если $\left( X^T X \right)^{-1}$ не существует, нужно вычислить [псевдообратную](https://ru.wikipedia.org/wiki/Псевдообратная_матрица) матрицу. ВременнАя сложность решения задачи линейной регрессии р
Я не совсем понял вопрос. Нужно вычислить (X^T X)^(-1), т.е. обратную к (X^T X). Если обратной к (X^T X) не существует, нужно вычислить [псевдообратную](https://ru.wikipedia.org/wiki/%D0%9F%D1%81%D0%B5%D0%B2%D0%B4%D0%BE%D0%BE%D0%B1%D1%80%D0%B0%D1%82%D0%BD%D0%B0%D1%8F_%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86%D0%B0) к (X^T X). Причём тут тройное произведение (X^T X) X^T ?

2021-12-26 09:28 UTC, Randl commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Если $\left( X^T X \right)^{-1}$ не существует, нужно вычислить [псевдообратную](https://ru.wikipedia.org/wiki/Псевдообратная_матрица) матрицу. ВременнАя сложность решения задачи линейной регрессии р
При том что выражение перед Y это уже псевдообратная X. "чтобы посчитать псевдообратную, надо посчитать псевдообратную" это бессмысленно. Кроме того, чтобы посчитать псевдообратную от X -- (X^T X)^(-1) X^T, явно обратную матрицу считать не надо.

2021-12-26 09:45 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Если $\left( X^T X \right)^{-1}$ не существует, нужно вычислить [псевдообратную](https://ru.wikipedia.org/wiki/Псевдообратная_матрица) матрицу. ВременнАя сложность решения задачи линейной регрессии р
Спасибо, теперь понял. Но почему тогда принято писать явное выражение
w = (X^T X)^(-1) X^T Y
вместо
w = pseudoinverse(X) Y
?

2021-12-26 09:50 UTC, Randl commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Если $\left( X^T X \right)^{-1}$ не существует, нужно вычислить [псевдообратную](https://ru.wikipedia.org/wiki/Псевдообратная_матрица) матрицу. ВременнАя сложность решения задачи линейной регрессии р
Хз, мб потому что явное лучше неявного, да и псевдообратные разные есть.

2021-12-26 10:03 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Если $\left( X^T X \right)^{-1}$ не существует, нужно вычислить [псевдообратную](https://ru.wikipedia.org/wiki/Псевдообратная_матрица) матрицу. ВременнАя сложность решения задачи линейной регрессии р
Нужно ли поправить текст? Если да, каким образом?

Допустим, кто-то хочет явно вычислить выражение перед Y. Допустим, он сначала считает (X^T X) и пытается найти обратную непосредственно. (X^T X относительно маленькая, d*d.) Если обратная существует, всё ок. Если нет, то можно
- отбросить всю затею с вычислением (X^T X)^(-1) X^T и считать pseudoinverse(X) каким-то образом;
- либо всё-таки посчитать псевдообратную именно к квадратной X^T X (взять сингулярное разложение и т.п.) и продолжить вычисления.

Формально всё-таки нет ошибки сейчас? Или написано бессмысленно?

2021-12-26 10:17 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +- $d$ -- количество признаков (*features*) для семплов в обучающем наборе, $d \in \{1, 2, \dotsc\}$;
"Семпл" встречается около 17 раз, много. Можно заменить везде на "пример" или "обучающий пример", но как-то громоздко звучать будет.
Действительно важно заменить на совсем русское? Или не будем придавать большого значения такого рода стилистике?

2021-12-26 10:45 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +не зависит. Семплы, соответствующие $\lambda_i > 0$, называются *опорными*. В статье {cite}`qubo3mlproblems2021` при переходе к QUBO-формулировке ограничение $\sum_{i} \lambda_i y_i = 0$ отбрасывают
Но мой комментарий ("Возможно, это обосновывается ..."), конечно, сомнительный.

2021-12-26 11:14 UTC, Randl commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Если $\left( X^T X \right)^{-1}$ не существует, нужно вычислить [псевдообратную](https://ru.wikipedia.org/wiki/Псевдообратная_матрица) матрицу. ВременнАя сложность решения задачи линейной регрессии р
В целом выражение `(X^T X)^(-1) X^T` имеет смысл только если `X^T X` обратима. Вся идея в том что мы предполагаем что можем обратить `X^T X` и поэтому домножаем обе стороны на `X^T`:
```
Xw = Y
X^T Xw = X^T Y
w = (X^T X)^(-1) X^T X w = (X^T X)^(-1) X^T Y
```
писать выражение `(X^T X)^{+} X^T` мне кажется смысла особого нет, так как вся история с домножением на `X^T` смысла не несет. В целом SVD под капотом находит собственные значения `X^T X` если я правильно помню?

2021-12-26 11:29 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Если $\left( X^T X \right)^{-1}$ не существует, нужно вычислить [псевдообратную](https://ru.wikipedia.org/wiki/Псевдообратная_матрица) матрицу. ВременнАя сложность решения задачи линейной регрессии р
Насколько понимаю, [да](https://en.wikipedia.org/wiki/Singular_value_decomposition#Calculating_the_SVD)

2021-12-26 11:43 UTC, alexey-pronkin commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +не зависит. Семплы, соответствующие $\lambda_i > 0$, называются *опорными*. В статье {cite}`qubo3mlproblems2021` при переходе к QUBO-формулировке ограничение $\sum_{i} \lambda_i y_i = 0$ отбрасывают
Забавно, что у них на arxiv лежит версия вообще без этого https://arxiv.org/abs/2008.02369
Но в самой статье на nature есть слова о том, что максимум ищется при том условии, что сумма произведений ламбд и y равна нулю.. 
Хз, для их анализа достаточно того, что на arxiv лежит, а как именно оптимально это сделать на QC это уже другой разговор

2021-12-26 11:53 UTC, alexey-pronkin commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +не зависит. Семплы, соответствующие $\lambda_i > 0$, называются *опорными*. В статье {cite}`qubo3mlproblems2021` при переходе к QUBO-формулировке ограничение $\sum_{i} \lambda_i y_i = 0$ отбрасывают
Да, ты прав, что это никак не отбрасывается.

2021-12-26 12:20 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +- $d$ -- количество признаков (*features*) для семплов в обучающем наборе, $d \in \{1, 2, \dotsc\}$;
лучше заменить, а то англицизмов и так полно и режет ухо

2021-12-26 12:22 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +где $y_i^{(pred)}$ -- предсказываемое значение, $y_i$ -- ground truth значение, $\braket{\cdot, \cdot}$ -- скалярное произведение. Удобно сразу избавиться от слагаемого $b$ (*bias*), добавив единицу
> \cdot -- это такой placeholder, т.е. показывает, что на этом месте должна быть переменная (или выражение).

не сразу понял что имел в виду это

2021-12-26 12:27 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Вектор $P$ содержит $m + 1 + l = K$ элементов. При подходящем выборе $m$ и $l$ достаточно точно выполняется равенство
возможно, но когда читал то не понял этого фокуса от слова совсем

2021-12-26 12:28 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Бинарные компоненты логично рассматривать как индикаторы наличия или отсутствия соответствующих степеней двойки в бинарном представлении каждого действительного числа. Введем вектор-столбец $P$ (*pre
мне из-за вот этих слов в лекции вообще сложно было её читать, ибо ещё требовалось переводить

2021-12-26 12:30 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +и матрицу $\mathcal{P}$ (*precision matrix*):
> Считай, дал точную цитату, чтобы читатель быстро увидел соответствие между лекцией и статьёй

думаешь что все пойдут читать ту статью, не думаю. лекция и так рыжая, которую нужно пару раз перечитывать

> Да и как ты хочешь перевести? "Матрица точности"? 

что плохого-то? мне вообще норм звучит, не нужно напрягать переводить

2021-12-26 12:33 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Нам потребуется избавиться от этих ограничений, чтобы получить *unconstrained* задачу. Для этого, как обычно, введем в минимизируемую квадратичную форму штрафы за нарушение ограничений. Вернемся к эт
> "выше ограничений" -- речевая ошибка.

возможно 

> чтобы получить неограниченную задачу" -- плохо звучит, необщепринято.

не думаю что «плохо звучит». конечно «необщепринято», покуда насобирали англицизмов этих и теперь вон «плохо».

2021-12-26 12:34 UTC, alexey-pronkin commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +и матрицу $\mathcal{P}$ (*precision matrix*):
Мне нравится как было первоначально, так проще запоминать буквенные обозначения
P - **P**recision matrix

2021-12-26 14:08 UTC, alexey-pronkin commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Нам потребуется избавиться от этих ограничений, чтобы получить *unconstrained* задачу. Для этого, как обычно, введем в минимизируемую квадратичную форму штрафы за нарушение ограничений. Вернемся к эт
Это не неограниченная задача, а задача без (дополнительных) ограничений

2021-12-26 14:37 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Нам потребуется избавиться от этих ограничений, чтобы получить *unconstrained* задачу. Для этого, как обычно, введем в минимизируемую квадратичную форму штрафы за нарушение ограничений. Вернемся к эт
Да, именно. Если вставить буквальный перевод вместо unconstrained, получилось бы "Нам потребуется избавиться от этих ограничений, чтобы получить задачу без ограничений". Бессмысленно ведь? Поэтому я и оставил "unconstrained", ссылаясь на "U" в QUBO.

2021-12-26 14:54 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Вектор $P$ содержит $m + 1 + l = K$ элементов. При подходящем выборе $m$ и $l$ достаточно точно выполняется равенство
https://github.com/quantum-ods/qmlcourse/commit/4d99e7e496a76cf849053262fc1e4df84f52f2f0

2021-12-26 14:59 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +где $y_i^{(pred)}$ -- предсказываемое значение, $y_i$ -- ground truth значение, $\braket{\cdot, \cdot}$ -- скалярное произведение. Удобно сразу избавиться от слагаемого $b$ (*bias*), добавив единицу
Ты нажмёшь "resolve conversation" в ветках к пунктам, где обсуждение завершено и ты согласен, что дальнейшие правки не нужны?
Или мне нажать "resolve conversation"?
Слишком много веток, хочу оставить только актуальные.

2021-12-26 15:29 UTC, alexey-pronkin commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Если $\left( X^T X \right)^{-1}$ не существует, нужно вычислить [псевдообратную](https://ru.wikipedia.org/wiki/Псевдообратная_матрица) матрицу. ВременнАя сложность решения задачи линейной регрессии р
Псевдообразная к X^T X вычислительно обычно превращается в L1 регуляризацию. А так вообще линейную регрессию для разных случаев считают всеми доступными методами, не только SVD: https://www.netlib.org/lapack/lug/node27.html

2021-12-26 15:46 UTC, alexey-pronkin commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +1. Затраты времени для конвертации задачи регрессии в QUBO-формулировку. Здесь получаем $\mathcal{O}(N K^2 d^2)$ (проверьте это, оценив число умножений, необходимых для вычисления $\mathcal{P}^T X^T
Я все-таки считаю, что усилия слишком большие, без бумажки такое не сделать. Усилия лучше перенести в новые домашки.
Можно тут и затронуть вопрос с очередностью вычисленийб т.к. произведение матриц ассоциативно, сделать численный пример, что результата можно и не дождаться, если тут поставить неправильно скобки

2021-12-26 16:00 UTC, alexey-pronkin commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Бинарные компоненты логично рассматривать как индикаторы наличия или отсутствия соответствующих степеней двойки в бинарном представлении каждого действительного числа. Введем вектор-столбец $P$ (*pre
может так?
```suggestion
Бинарные компоненты логично рассматривать как индикаторы наличия или отсутствия соответствующих степеней двойки в бинарном представлении каждого действительного числа. Введем вектор-столбец $P$, который отвечает за точность представления (_**P**recision vector_) и состоит из степеней двойки со знаками:
```

2021-12-26 16:51 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Нам потребуется избавиться от этих ограничений, чтобы получить *unconstrained* задачу. Для этого, как обычно, введем в минимизируемую квадратичную форму штрафы за нарушение ограничений. Вернемся к эт
не утверждал бы так, это просто структура языка такая, что нормально

2021-12-26 16:53 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +где $y_i^{(pred)}$ -- предсказываемое значение, $y_i$ -- ground truth значение, $\braket{\cdot, \cdot}$ -- скалярное произведение. Удобно сразу избавиться от слагаемого $b$ (*bias*), добавив единицу
часть ты уже сделал, а часть закрыл. те что открыты кажется ещё не закончены (но возможно что-то пропустил)

2021-12-26 16:56 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Бинарные компоненты логично рассматривать как индикаторы наличия или отсутствия соответствующих степеней двойки в бинарном представлении каждого действительного числа. Введем вектор-столбец $P$ (*pre
хоть что-то, `P` можно и не выделять

2021-12-26 17:29 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Бинарные компоненты логично рассматривать как индикаторы наличия или отсутствия соответствующих степеней двойки в бинарном представлении каждого действительного числа. Введем вектор-столбец $P$ (*pre
Принял вариант Алексея.

2021-12-26 17:49 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +не зависит. Семплы, соответствующие $\lambda_i > 0$, называются *опорными*. В статье {cite}`qubo3mlproblems2021` при переходе к QUBO-формулировке ограничение $\sum_{i} \lambda_i y_i = 0$ отбрасывают
Ну, не знаю, лучше бы с двойственной задачей работать.
Всё-таки вариант в Nature следует считать "чистовым", а на arxiv -- "черновым". В Nature и опубликовано позже.
Может, они просто забыли про это ограничение? И мне следует самостоятельно допилить их статью, введя квадратичный штраф вместо этого ограничения, и включив этот штраф в итоговую QUBO-формулировку?

2021-12-27 06:52 UTC, alexey-pronkin commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +не зависит. Семплы, соответствующие $\lambda_i > 0$, называются *опорными*. В статье {cite}`qubo3mlproblems2021` при переходе к QUBO-формулировке ограничение $\sum_{i} \lambda_i y_i = 0$ отбрасывают
А почему ты думаешь, что применять квантовый отжиг эффективнее будет двойственную задачу? Надо бы тогда ещё и сравнить оба подхода 😂

2021-12-27 07:05 UTC, alexey-pronkin commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +и матрицу $\mathcal{P}$ (*precision matrix*):
```suggestion
и матрицу точности $\mathcal{P}$ (_**P**recision matrix_), которая задает переход к бинарному представлению векторов:
```

2021-12-27 07:06 UTC, alexey-pronkin commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +и матрицу $\mathcal{P}$ (*precision matrix*):
```suggestion
и матрицу точности $\mathcal{P}$ (_**P**recision matrix_), которая задает переход к бинарному представлению векторов:
```

2021-12-27 08:01 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +не зависит. Семплы, соответствующие $\lambda_i > 0$, называются *опорными*. В статье {cite}`qubo3mlproblems2021` при переходе к QUBO-формулировке ограничение $\sum_{i} \lambda_i y_i = 0$ отбрасывают
В arxiv-статье у них написано, что требуемое число кубитов O(N^2 K^2). А в Nature-статье (двойственная задача) число кубитов O(K^2 d^2), это точно лучше.

2021-12-27 08:02 UTC, SemyonSinchenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +не зависит. Семплы, соответствующие $\lambda_i > 0$, называются *опорными*. В статье {cite}`qubo3mlproblems2021` при переходе к QUBO-формулировке ограничение $\sum_{i} \lambda_i y_i = 0$ отбрасывают
Мож авторам письмо написать? Все же статья свежая довольно, должны ответить.

2021-12-27 09:34 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +не зависит. Семплы, соответствующие $\lambda_i > 0$, называются *опорными*. В статье {cite}`qubo3mlproblems2021` при переходе к QUBO-формулировке ограничение $\sum_{i} \lambda_i y_i = 0$ отбрасывают
Доделал сам, оказалось просто. Проверьте, пожалуйста: https://github.com/quantum-ods/qmlcourse/pull/365/commits/7179dfaa7c8ca3fa0d57a2191abad1dc865b30ca

2021-12-27 12:47 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +1. Затраты времени для конвертации задачи регрессии в QUBO-формулировку. Здесь получаем $\mathcal{O}(N K^2 d^2)$ (проверьте это, оценив число умножений, необходимых для вычисления $\mathcal{P}^T X^T
Тогда на усмотрение @SemyonSinchenko 
(Лекция "оранжевая", при разборе можно не стесняться написать на бумажке несколько строк, на мой взгляд.)
(К тому же, в домашки плохо переносятся задачи вида "докажите, что...")

2021-12-27 13:37 UTC, SemyonSinchenko approved these changes

2021-12-27 20:28 UTC, alexey-pronkin approved these changes

2021-12-28 07:00 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +- $d$ -- количество признаков (*features*) для семплов в обучающем наборе, $d \in \{1, 2, \dotsc\}$;
https://github.com/quantum-ods/qmlcourse/pull/365/commits/7bf75e3f1bb66fd98f81c4c3ca16b85651a16608

2022-01-03 13:26 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Если $\left( X^T X \right)^{-1}$ не существует, нужно вычислить [псевдообратную](https://ru.wikipedia.org/wiki/Псевдообратная_матрица) матрицу. ВременнАя сложность решения задачи линейной регрессии р
к чему пришли в итоге?

2022-01-03 13:28 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Нам потребуется избавиться от этих ограничений, чтобы получить *unconstrained* задачу. Для этого, как обычно, введем в минимизируемую квадратичную форму штрафы за нарушение ограничений. Вернемся к эт
«unconstrained» всё же предлагаю написать по-русски

2022-01-04 13:59 UTC, alexey-pronkin commented
Что с ударениями, оставляем как есть?

2022-01-04 14:10 UTC, vtrokhymenko commented
> Что с ударениями, оставляем как есть?

предлагаю вообще убрать, то бишь с бОльше --> больше

2022-01-07 12:23 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Если $\left( X^T X \right)^{-1}$ не существует, нужно вычислить [псевдообратную](https://ru.wikipedia.org/wiki/Псевдообратная_матрица) матрицу. ВременнАя сложность решения задачи линейной регрессии р
Мне кажется, серьёзных ошибок сейчас нет (по крайней мере, у нас не та лекция, где нужно на полную глубину погружаться в классические алгоритмы для классических ML-задач).
@Randl - если считаешь, что нужны изменения, исправь, пожалуйста.
В общем, предлагаю оставить на усмотрение @Randl и @Yorko

2022-01-07 12:31 UTC, dmburd commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Нам потребуется избавиться от этих ограничений, чтобы получить *unconstrained* задачу. Для этого, как обычно, введем в минимизируемую квадратичную форму штрафы за нарушение ограничений. Вернемся к эт
https://github.com/quantum-ods/qmlcourse/pull/365/commits/798c4b604333f9aa74504edef00689ebba88abb4

2022-01-07 12:34 UTC, dmburd commented
Ударения -- на ваше усмотрение, но хотелось бы, чтобы смысл слов был однозначно понимаемый.

2022-01-13 20:37 UTC, vtrokhymenko commented on qmlcourseRU/book/problems2qml/qubo_linreg_svm_kmeans.md
> +Если $\left( X^T X \right)^{-1}$ не существует, нужно вычислить [псевдообратную](https://ru.wikipedia.org/wiki/Псевдообратная_матрица) матрицу. ВременнАя сложность решения задачи линейной регрессии р
#369

2022-01-13 20:38 UTC, merged